# Gradle
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8

# Project
mod_id=autobattle
mod_version=0.1.0
maven_group=dev.kardane.autobattle
archives_base_name=AutoBattle

# Fabric / Minecraft
minecraft_version=1.21.8
loader_version=0.18.0
loom_version=1.15.5

# Fabric API / external mods
fabric_api_version=0.136.0+1.21.8
openai_java_version=4.65.0
caffeine_version=3.2.4
disguiselib_release_tag=v1.21.8.7
disguiselib_version=1.3.12-1.21.8
gcb_server_version=1.0.1+1.21.8
danta_shader_version=1.0.2+1.21.8
rgbmaputils_version=1.0.0+1.21.8

# Polymer
polymer_version=0.13.9+1.21.8
polymer_blocks_version=0.13.13+1.21.8
polymer_resource_pack_version=0.13.13+1.21.8
polymer_virtual_entity_version=0.13.9+1.21.8
polymer_autohost_version=0.13.13+1.21.8

# Patbox utilities
sgui_version=1.10.2+1.21.8
placeholder_api_version=2.7.2+1.21.8
server_translations_api_version=2.5.1+1.21.5
map_canvas_api_version=0.5.1+1.21.5
player_data_api_version=0.8.0+1.21.6
predicate_api_version=0.6.0+1.21.2

# Permissions
fabric_permissions_api_version=0.4.0

# Java
java_version=21
